{% set name = "bigbrother" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 61d442e68648d83b18dab082f0497c8ba987b41b7fb5cc3546c0f94b57caf213

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pydantic

test:
  imports:
    - bigbrother

about:
  home: http://github.com/timkpaine/bigbrother
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A library for object observability
  description: A library for object observability
  dev_url: https://github.com/timkpaine/bigbrother

extra:
  recipe-maintainers:
    - timkpaine
